layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: sinajams
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: sjamstweets
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: AI Robot (individual)
    web_url: https://vimeo.com/363058196
    image_url: robot.jpg

  - name: Cypress Mobile App (team of 6)
    web_url: https://apps.apple.com/ca/app/cypress-visual-sensor/id1426892725
    image_url: cypress.png

  - name: AI Education Kit (team of 2)
    web_url: http://altumview.com/education.html
    image_url: kit.png
